---
- name: Install and configure k3s cluster on Alpine Linux
  hosts: all
  become: true
  vars:
    k3s_token: myk3stoken
    master_ip: "{{ hostvars[groups['masters'][0]]['ansible_host'] }}"
    node_ips: "{{ groups['nodes'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
  
  tasks:
    - name: Enable community repo
      replace:
        path: /etc/apk/repositories
        regexp: '#'
        replace: " "
  
    - name: Install required packages
      apk:
        name: "{{ item }}"
      loop:
        - curl
        - iptables
        - tailscale
      
    - name: Install k3s
      shell: curl -fsSL https://get.k3s.io | ash
      args:
        creates: /usr/local/bin/k3s
      
    - name: Retrieve the node token from the master
      command: cat /var/lib/rancher/k3s/server/node-token
      register: node_token
      when: "'master' in group_names"
      
    - name: Configure master node
      shell: k3s server --cluster-init --token {{ k3s_token }} --forc
      when: "'master' in group_names"
      
    - name: Fetch the master node's IP
      shell: tailscale ip -4
      changed_when: false
      register: master_ip
      
    - name: Join worker nodes to the master
      shell: curl -sfL https://get.k3s.io | K3S_URL="https://{{ master_ip.stdout }}:6443" K3S_TOKEN="{{ node_token.stdout }}" INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" ash -
      when: "'nodes' in group_names"
