---
- name: Install dependencies
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install required packages
      apk:
        name: 
          - curl
          - iptables
        state: present
        
- name: Install K3s on servers
  hosts: server
  become: true
  tasks:
    - name: Install K3s on the server
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Retrieve the K3s server token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_server_token

    - name: Register local IP to connect to master
      debug: var=hostvars[server]['ansible_default_ipv4']['address']
      register: k3s_server_ip

    - debug:
        var: '{{item}}'
      with_items:
        - k3s_server_ip.stdout
        - k3s_server_token.stdout

- name: Join K3s agents to the cluster
  hosts: agent
  become: true
  tasks:
    - name: Install K3s on the agent
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_server_ip.stdout }}:6443 K3S_TOKEN={{ k3s_server_token.stdout }} sh -
