---
- name: Install dependencies
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install required packages
      apk:
        name: 
          - curl
          - iptables
        state: present
        
- name: Install K3s on servers
  hosts: server
  become: true
  tasks:
    - name: Install K3s on the server
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /var/lib/rancher/k3s/server/node-token

    - name: Wait for node-token file to be created
      wait_for:
        path: /var/lib/rancher/k3s/server/node-token

    - name: Retrieve the K3s server token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
    - set_fact:
        k3s_server_token: "{{ k3s_token.stdout }}"

    - name: Register local IP to connect to master
      #set_fact: 
      #  k3s_server_ip: "{{ ansible_default_ipv4.address }}"
      debug: 
        msg: "{{ ansible_default_ipv4.address }}"

- name: Join K3s agents to the cluster
  hosts: agent
  become: true
  tasks:  
    - name: Install K3s on the agent
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://"{{ hostvars['k3s-server']['k3s_server_ip'] }}":6443 K3S_TOKEN="{{ hostvars['k3s-server']['k3s_server_token'] }}" sh -
