---
- name: Install dependencies
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Enable community repo
      replace:
        path: /etc/apk/repositories
        regexp: '#'
        replace: ''

    - name: Install required packages
      apk:
        name: 
          - curl
          - docker
          - tailscale
        state: present
        
- name: Install Docker on servers
  hosts: server
  become: true
  tasks:
    - name: Wait for Docker to be installed
      wait_for:
        path: /var/lib/docker

    - name: Initialize cluster
      shell: docker swarm init --advertise-addr tailscale0

    - name: Retrieve the swarm join token
      shell: docker swarm join-token worker -q
      register: swarm_token
    - set_fact:
        swarm_join_token: "{{ swarm_token.stdout }}"

- name: Join swarm agents to the cluster
  hosts: agent
  become: true
  tasks:
    - name: Join cluster
      shell: docker swarm join --token "{{ swarm_join_token }}" "{{ hostvars['swarm-0']['ansible_tailscale0.ipv4.address'] }}"