---
- name: Install dependencies
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Enable community repo
      replace:
        path: /etc/apk/repositories
        regexp: '#'
        replace: ''

    - name: Install required packages
      apk:
        name: 
          - curl
          - docker
          - tailscale
          - glusterfs-server
        state: present
        
- name: Install Docker on servers
  hosts: master # swarm-0
  become: true
  tasks:
    - name: Wait for Docker to be installed
      wait_for:
        path: /var/lib/docker

    - name: Initialize cluster
      shell: docker swarm init --advertise-addr tailscale0

    - name: Retrieve the manager join token
      shell: docker swarm join-token manager -q
      register: manager_token
    - set_fact:
        manager_join_token: "{{ manager_token.stdout }}"

    - name: Retrieve the worker join token
      shell: docker swarm join-token worker -q
      register: worker_token
    - set_fact:
        worker_join_token: "{{ worker_token.stdout }}"

- name: Join managers to the cluster
  hosts: managers # swarm-{1-2}
  become: true
  tasks:
    - name: Join cluster
      shell: docker swarm join --token "{{ manager_join_token }}" "{{ hostvars['swarm-0']['ansible_tailscale0.ipv4.address'] }}:2377"

- name: Join agent to the cluster
  hosts: agent # swarm-3
  become: true
  tasks:
    - name: Join cluster
      shell: docker swarm join --token "{{ worker_join_token }}" "{{ hostvars['swarm-0']['ansible_tailscale0.ipv4.address'] }}:2377"

- name: Setup GlusterFS
  hosts: all
  become: true
  tasks:
    - name: 